### ISSUE TITLE
Class com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem not found

### ISSUE THREAD

**Issue by smic-jurigutierrez** [jaumpedro214/posts#10]
Hi,

Your posts are very helpful for us who are trying to setup spark on local env. Thank you.
I'm now trying to connect to gcs but got an error `java.lang.RuntimeException: java.lang.ClassNotFoundException: Class com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem not found`
May reference git repo: **data_pipeline_spark_gcs_gbq**

I'm running it on Jupyter. What could be missing?
Regards,

**Comment by jaumpedro214** [comment]
Hello, 

First of all, thanks for the words, I'm glad to hear that my posts are helping.

This issue occurs probably because Spark was not properly configured with the Jars to establish a connection with GCS.

To solve, just download the GCS connection jar:
https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-latest-hadoop2.jar

And put it in the folder $SPARK_HOME/jars folder
This needs to be done in the same machine where the Jupyter server + spark client are installed.

My references are [this post](https://kashif-sohail.medium.com/read-files-from-google-cloud-storage-bucket-using-local-pyspark-and-jupyter-notebooks-f8bd43f4b42e) and the official [GCP connector docs](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/INSTALL.md).

Hope it helps,

**Comment by smic-jurigutierrez** [comment]
Hi @jaumpedro214,

Thank you so much, I missed to put the jar on the Jupyter server.
It works perfectly now.

Regards,
